name: Terraform Deployment Workflow

on:
  push:
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.IAM_ROLE }}
        audience: sts.amazonaws.com

    - name: Terraform Initialize
      run: terraform init -backend-config="bucket=project-x-dev-state-vss" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"

    - name: Terraform Plan
      run: terraform plan -var-file="roots/main-eks-root/homework-project-vss.tfvars" -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve "tfplan"
