
name: Terraform Deployment Workflow

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["*"]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Select environment based on branch pushed
    environment: ${{ (github.ref == 'refs/heads/main' && 'dev') || (github.ref == 'refs/heads/prod' && 'production') }}

    steps:
      - name: AWS Loggin
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE }}
          role-session-name: githubactionsbot 
          aws-region: "us-east-1"

      - name: clone repo 
        uses: actions/checkout@v4

      - name: initialize Terraform
        run: terraform init 
        working-directory: ./root/main-eks-root

      - name: Plan execution
        run: terraform plan -var-file="homework-project.vss.auto.tfvars"
        working-directory: ./root/main-eks-root

      # - name: execute terraform
      #   run: terraform apply -var-file="homework-project.notyouraverageusername.auto.tfvars" -auto-approve
      #   working-directory: ./root/main-eks-root
      
      # - name: destroy infrastructure
      #   run: terraform destroy -auto-approve
      #   working-directory: ./root/main-eks-root