name: Terraform Deployment Workflow

on:
  push:
    branches:
      - "*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'dev') || (github.ref == 'refs/heads/prod' && 'production') }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: "us-east-1"

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./root/main-eks-root

      - name: Plan Execution
        run: terraform plan -var-file="homework-project.vss.auto.tfvars"
        working-directory: ./root/main-eks-root

      # Uncomment and configure as needed
      # - name: Apply Terraform
      #   run: terraform apply -var-file="homework-project.vss.auto.tfvars" -auto-approve
      #   working-directory: ./root/main-eks-root

      # - name: Destroy Infrastructure
      #   run: terraform destroy -auto-approve
      #   working-directory: ./root/main-eks-root
